name: Build and Release a clean version of Rubeus

on:
  push:
    branches:
      - obfuscation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: obfuscation  # Specify the branch to checkout

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          files: |
            ./Rubeus/bin/Release/Rubeus.exe
          token: ${{ secrets.GITHUB_TOKEN }}
